import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';
import { useRouter } from 'next/router'
import styles from '@/src/styles/Home.module.css'
import logo from '../../public/images/logo_red.png'
import { getAuth, createUserWithEmailAndPassword } from "firebase/auth";
import { Layout, Row, Col, Spin, notification, Card, message } from 'antd';
import React, { useEffect, useState } from 'react'
// import auth from '../firebase/config'
import app from '../firebase/config'

const { Header, Content } = Layout;

export default function Login() {
  const router = useRouter()
  const [loading, setLoading] = useState(false);
  const [messageApi, contextHolder] = message.useMessage();

  const handleLogin = (event) => {
    setLoading(true)
    event.preventDefault()
    let email = document.forms["loginForm"]["username"].value;
    let password = document.forms["loginForm"]["password"].value;
    if (email == "" || password == "") {
      alert("Please complete all fileds");
      setLoading(false)
      return false;
    }
    const auth = getAuth(app);
    const request = createUserWithEmailAndPassword(auth, email, password)
    .then((userCredential) => {
      const user = userCredential.user;
      console.log(user)
      router.push('/home')
      setLoading(false)
    })
    .catch((error) => {
      const errorCode = error.code;
      const errorMessage = error.message;
      messageApi.open({content:errorCode, type:'error', duration:3});
      console.log(errorCode)
      setLoading(false)
    });
  } 

  return <>
  {contextHolder}
    <Head>
      <title>だんだん</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Layout>
      <Header className={styles.headerStyle} style={{backgroundColor:'white'}}>
        <Image alt='logo' height={50} src={logo} />
        <div>
          <div></div>
          <div></div>
        </div>
      </Header>
      <div className={styles.bar}></div>
      
      <Content>
        <Spin spinning={loading}>
            <Link href={'/home'}></Link>
          <form className={styles.songForm} name='loginForm' onSubmit={handleLogin}>
            <label>Email</label>
            <input type='text' id='username' name='username'/>
            <label>Password</label>
            <input type='text' id='password' name='password'/>
            <button type='submit'>Submit</button>  
          </form> 
        </Spin>
      </Content>
    </Layout>
  </>
}
