import React, { useEffect, useState } from 'react'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { Spin, Button, Result, Skeleton, Layout, Progress } from 'antd';
import { CommonFoot } from '../utils/methods'
import Image from 'next/image'
import styles from '@/src/styles/Home.module.css'
import { SpacedRepetition } from '../utils/methods';

const { Header, Footer, Content } = Layout; 

export default function Results () {
  const [sloading, setsLoading] = useState(true);
  const router = useRouter()
  const {query: {totalW, totalC}} = router 


  useEffect(()=>{
    setTimeout(() => {
      setsLoading(false)
    }, 1000);
  },[])

  return (<>
  {/* <Spin spinning={sloading}> */}
    <Head>
      <title>だんだん</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Header className={styles.headerStyle} style={{backgroundColor:'white'}}>
      <Image alt='logo' width={120} height={50} src="/images/logo_red.png" />
    </Header>
    <div className={styles.bar}></div>
    <div style={{height:'200px'}}></div>
    <center style={{flex:'1 0', display:'flex', flexDirection:'column'}}>
      <Skeleton loading={sloading} active>
        {console.log((totalC/(totalC+totalW))*100)}
        {console.log(totalC)}
        {console.log(totalW)}
        {console.log((Number(totalC)/(Number(totalW)+Number(totalC))*100))}
      <Result
        status="success"
        title="Study Complete!"
        // subTitle="You have completed this flashcard set. Go to the dashboard to see your progress."
        subTitle={<>
          <p>Wrong:{totalW}</p>
          <p>Correct:{totalC}</p>
        </>}
        extra={[
          //<Button type="primary" onClick={()=>{SpacedRepetition()}}>Go Home</Button>,
          <Button type="primary" onClick={()=>{router.push('/home')}}>Go Home</Button>,
          <Button onClick={()=>{router.back()}}>Study Again</Button>,
        ]}
      />
      {/* <div style={{width:'50%'}}><Progress percent={(Number(totalC)/(Number(totalW)+Number(totalC))*100)}></Progress></div> */}
      
      </Skeleton>
    </center>
    <div style={{height:'200px'}}></div>
    <CommonFoot/>
    {/* </Spin> */}
  </>)
}