import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import styles from '@/src/styles/Home.module.css'
import styles2 from '@/src/styles/FlashCard.module.css'
import React, { useEffect, useState } from 'react'
import { Layout, Row, Col, Spin, notification, Card } from 'antd';
import { getData } from '@/src/firebase/firestore/getData'
import { isKanji, getKanjiInfo, KanjiList, flashCardDoc, FlashSets, CommonFoot } from '../../utils/methods'
import { CheckOutlined, CloseOutlined } from '@ant-design/icons';

const { Header, Footer, Content } = Layout;

export default function FlashCardSet() {
  return (
    <>
    <Head>
      <title>だんだん</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Header className={styles.headerStyle} style={{backgroundColor:'white'}}>
      <Image alt='logo' width={120} height={50} src="/images/logo_red.png" />
    </Header>
      <div className={styles.bar}></div>
{/*  //////////////////////////////////////////////////////////////////////////////////// */}
    <div className={styles.cont}>
    {/* <div className={styles.cont}> */}
      <Card id='flipCard' className={[styles.crd]} onClick={()=>{
      // <Card id='flipCard' className={[styles.flipCard, styles.front]} onClick={()=>{
        // document.getElementById('flipCard').classList.toggle(styles.chg);
        document.getElementById('flipCard').classList.toggle(styles.back);
    }}>
        <div className={styles.front}></div>
        <div className={styles.back}> byyee back</div>
      </Card>
    </div>


{/*  //////////////////////////////////////////////////////////////////////////////////// */}
    <Content>
      <div className={[styles.space]} style={{display:'flex', flexDirection:'row', justifyContent:'center', padding:'20px 20px'}}>

        {/* <Card className={styles2.flashcardBox} style={{width:'500px', height:'300px', display:'flex', flexDirection:'column', justifyContent:'center', alignItems:"center"}}>
          <div className={styles2.flashcardInner}>
            <div className={styles2.flashcardFront}>Hiii this is the front</div>
            <div className={styles2.flashcardBack}>byyeee this is the back</div>
          </div>
        </Card> */}

      </div>
      <div style={{display:'flex', flexDirection:'row', justifyContent:'center', padding:'20px 20px'}}>
        <CheckOutlined />
        <CloseOutlined />
      </div>
    </Content>
      <CommonFoot/>
    </>
  )
}